[build]
command = "pip install -r requirements.txt && mkdir -p functions && cp -r * functions/"
publish = "public"
functions = "functions"

[build.environment]
PYTHON_VERSION = "3.9"
NETLIFY_USE_PNPM = "false"
NETLIFY_USE_YARN = "false"
NETLIFY_USE_NPM = "false"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200

[functions]
directory = "functions"
node_bundler = "esbuild"

[dev]
framework = "#custom"
command = "python app.py"
targetPort = 5000
port = 8888
publish = "public" 